# Generated by Django 5.2.1 on 2025-05-26 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('cheque_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salary', 'Staff Salary'), ('rent', 'Rent'), ('petrol', 'Petrol'), ('utility', 'Utility Bills'), ('supplies', 'Office Supplies'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('medicine_list', models.TextField()),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cheque', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chequedetails')),
                ('medical_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicalshop')),
            ],
        ),
        migrations.CreateModel(
            name='PartialPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_payments', to='core.income')),
            ],
        ),
    ]
