# Generated by Django 5.2.1 on 2025-05-27 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partialpayment',
            name='income',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_partial_payments', to='core.income'),
        ),
        migrations.CreateModel(
            name='IncomePartialPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_partial_payments', to='core.income')),
            ],
        ),
    ]
