# Generated by Django 5.2.1 on 2025-05-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_partialpayment_income_incomepartialpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='medicine_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
